### ISSUE TITLE
New address family defined, please update secclass_map

### ISSUE THREAD

**Issue by LMAO-armv8** [manudinath/android_kernel_samsung_f41#1]
In file included from /hdd/los-q/kernel/samsung/f41/scripts/selinux/genheaders/genheaders.c:19:0:                                                                             
/hdd/los-q/kernel/samsung/f41/security/selinux/include/classmap.h:247:2: error: #error New address family defined, please update seccless_map.
 #error New address family defined, please update secclass_map.                   

![Screenshot_20210905-160544_Termius](https://user-images.githubusercontent.com/82850873/132123764-81944e54-04a7-4dac-b1ac-d3bbacdca643.jpg)

**Comment by manudinath** [comment]
Fixed. Pull & rebuild
